### ISSUE TITLE
A way to pass params to a list of functions

### ISSUE THREAD

**Issue by MikaAK** [robertleeplummerjr/thaw.js#3]

**Comment by robertleeplummerjr** [comment]
How did you solve this?  Just curious.

**Comment by robertleeplummerjr** [comment]
Come to think of it, you could easily do:

new Thaw([
    function() {
        param1;param2;param3;
    },
    function() {
        param1;param2;param3;
    }
]);

**Comment by MikaAK** [comment]
The solution ended up being because just simply storing the object in an object first then just using the i returned to index through it. 

## EG
```javascript
var callbacks = [] //pretend this is full of items

thaw(callbacks, {
  each: function(i) {
    callbacks[i]()
  }
})
